spring:
  application:
    name: RATING-SERVICES
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      host: localhost
      port: 27017
      database: microservices
      repositories:
        enabled: true
  config:
    import: optional:configserver:http://localhost:8085

server:
  port: 9094  

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone : http://localhost:8761/eureka/